spring:
  application:
    name: stock-service
  config:
    import: optional:configserver:http://localhost:8888

  # Once done, put datasource and jpa in config server as 'stock-service.yml' inside src/resources/configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    password: latifa
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update