server:
  port: 8083

spring:
  application:
    name: payment-service
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:h2:mem:paymentdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jackson:
    serialization:
      write-dates-as-timestamps: false


paypal:
  client-id: "AXZqFJYZLJlfaz7O5UX7S6nccHVy68SAJ2rNIAVS_dyVqcrkRIkelVxDKSBRaFlJFvoh_Jh07wAhQcM6"
  client-secret: "EDgjElzwBMHD4w2K8KimKy2gtJ6EdZ7CuBZOf424xVqrIaBhqX2y0lSBn5di8yWDeVbl6a5lRgukz7Ii"
  mode: sandbox


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
