spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888

  # Once done, put datasource and jpa in config server as 'order-service.yml' inside src/resources/configurations
  datasource:
    url:
    password:
    username:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update